version: "3"
services:
  sq:
    build: ./squid
    hostname: squid
    volumes:
      - ./squid:/tmp/host
    privileged: true
  ab1:
    build: ./ab
    hostname: ab1
    volumes:
      - ./ab:/tmp/host
  ab2:
    build: ./ab
    hostname: ab2
    volumes:
      - ./ab:/tmp/host
  ab3:
    build: ./ab
    hostname: ab3
    volumes:
      - ./ab:/tmp/host
  web1:
    image: nginx:alpine
  web2:
    image: nginx:alpine
  web3:
    image: nginx:alpine
  web4:
    image: nginx:alpine
  web5:
    image: nginx:alpine
